CREATE TABLE OHIO_DW.CONV_CLASS_ENROLLMENT (
    CLASS_NBR INTEGER NULL,
    STUDENT_PID VARCHAR(50) NULL,
    TERM_CODE INTEGER NULL,
    ENRL_COURSE_LEVEL VARCHAR(50) NULL,
    ENRL_NEWTAX_LEVEL INTEGER NULL,
    ENRL_NEWTAX_MODEL VARCHAR(50) NULL,
    ENRL_NEWTAX_SUBJECT VARCHAR(255) NULL,
    SUBSIDY_ELIGIBLE_CODE INTEGER NULL,
    ENROLLED_FLAG INTEGER NULL,
    COMPLETED_FLAG INTEGER NULL,
    ENRLLD_CRDT_HRS INTEGER NULL,
    CMPLTD_CRDT_HRS INTEGER NULL,
    ENRLLD_WGHTD_CRDT_HRS INTEGER NULL,
    CMPLTD_WGHTD_CRDT_HRS INTEGER NULL,
    ENRLLD_COST_WGHTD_CRDT_HRS REAL NULL,
    CMPLTD_COST_WGHTD_CRDT_HRS REAL NULL,
    ENRLLD_REIM_WGHTD_CRDT_HRS REAL NULL,
    CMPLTD_REIM_WGHTD_CRDT_HRS REAL NULL,
    NONGRADED_FLAG VARCHAR(50) NULL,
    CRSE_GRADE_OFF VARCHAR(50) NULL
);

GRANT SELECT ON table ohio_dw.conv_class_enrollment TO PUBLIC;